import { notFound, redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { isGroupScoped } from "@/lib/rbac";
import { prisma } from "@/lib/prisma";
import { PrintButton } from "@/components/print-button";

export const dynamic = "force-dynamic";

/**
 * Print-optimized meeting minutes (SRS Module 5: instant PDF minutes).
 * Renders as a light-theme document; the Print button opens the browser's
 * print dialog for one-click save-as-PDF.
 */
export default async function MinutesPage({
  params,
}: {
  params: { id: string };
}): Promise<JSX.Element> {
  const user = await getSession();
  if (!user) redirect("/login");

  const meeting = await prisma.reviewMeeting.findUnique({
    where: { id: params.id },
    include: {
      chairedBy: { select: { name: true } },
      decisions: {
        // Tenant isolation: site-scoped users only see decisions about
        // projects within their own scope (own site + Group standards).
        where: isGroupScoped(user)
          ? {}
          : {
              project: user.siteId
                ? { OR: [{ siteId: user.siteId }, { scopeType: "GROUP" }] }
                : { scopeType: "GROUP" },
            },
        include: {
          project: { select: { code: true, title: true } },
          signedOffBy: { select: { name: true } },
        },
        orderBy: { createdAt: "asc" },
      },
    },
  });
  if (!meeting) notFound();

  return (
    <main className="min-h-screen bg-white p-8 text-black print:p-0">
      <div className="mx-auto max-w-3xl space-y-6">
        <div className="flex items-start justify-between print:hidden">
          <p className="text-sm text-neutral-500">OpsPM360 — printable minutes</p>
          <PrintButton />
        </div>

        <header className="border-b border-neutral-300 pb-4">
          <h1 className="text-2xl font-bold">IT Steering Committee — Meeting Minutes</h1>
          <p className="mt-2 text-sm text-neutral-600">
            Endeavour Mining Group · {meeting.meetingDate.toISOString().slice(0, 10)} · Chair:{" "}
            {meeting.chairedBy.name} ·{" "}
            {meeting.closedAt ? `Closed ${meeting.closedAt.toISOString().slice(0, 16).replace("T", " ")} UTC` : "In session"}
          </p>
        </header>

        <section>
          <h2 className="mb-2 text-lg font-semibold">
            Decision ledger ({meeting.decisions.length})
          </h2>
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b-2 border-neutral-400 text-left">
                <th className="py-2 pr-2">#</th>
                <th className="py-2 pr-2">Project</th>
                <th className="py-2 pr-2">Decision</th>
                <th className="py-2 pr-2">Action taken</th>
                <th className="py-2">Signed off by</th>
              </tr>
            </thead>
            <tbody>
              {meeting.decisions.map((d, i) => (
                <tr key={d.id} className="border-b border-neutral-200 align-top">
                  <td className="py-2 pr-2">{i + 1}</td>
                  <td className="py-2 pr-2">
                    <span className="font-mono text-xs">{d.project.code}</span>
                    <br />
                    {d.project.title}
                  </td>
                  <td className="py-2 pr-2 font-medium">
                    {d.decisionType.replaceAll("_", " ")}
                  </td>
                  <td className="py-2 pr-2">{d.actionTaken}</td>
                  <td className="py-2">{d.signedOffBy.name}</td>
                </tr>
              ))}
              {meeting.decisions.length === 0 ? (
                <tr>
                  <td colSpan={5} className="py-4 text-neutral-500">
                    No decisions recorded.
                  </td>
                </tr>
              ) : null}
            </tbody>
          </table>
        </section>

        {meeting.notes ? (
          <section>
            <h2 className="mb-2 text-lg font-semibold">Notes</h2>
            <p className="whitespace-pre-wrap text-sm">{meeting.notes}</p>
          </section>
        ) : null}

        <footer className="border-t border-neutral-300 pt-4 text-xs text-neutral-500">
          Generated by OpsPM360. All decisions are individually recorded in the immutable COBIT
          2019 audit trail.
        </footer>
      </div>
    </main>
  );
}
